### ISSUE TITLE
Python 3.10 (and thus also Arm Macs) not supported? 

### ISSUE THREAD

**Issue by Patronics** [coqui-ai/stt-model-manager#34]
The universal (Arm-compatible) version of stt is only available for python 3.10, while attempting to install this from pypi for python 3.10 fails with the error `ERROR: Cannot install coqui-stt-model-manager==0.0.10, coqui-stt-model-manager==0.0.11, coqui-stt-model-manager==0.0.12, coqui-stt-model-manager==0.0.14, coqui-stt-model-manager==0.0.15, coqui-stt-model-manager==0.0.16, coqui-stt-model-manager==0.0.17, coqui-stt-model-manager==0.0.18, coqui-stt-model-manager==0.0.8 and coqui-stt-model-manager==0.0.9 because these package versions have conflicting dependencies.`

and from attempting to build and install from source using "make install" from a fresh clone fails with the error `ERROR: Package 'coqui-stt-model-manager' requires a different Python: 3.10.2 not in '<3.10,>=3.6'`

**Comment by mcandre** [comment]
That patch is necessary but insufficient for M1 Macs.

Trace:

```console
$ cat requirements.txt
git+https://github.com/coqui-ai/stt-model-manager@d446b34c9e7aac2700c32ddd8574b783c81d86d8#egg=coqui-stt-model-manager

$ pip3 install -r requirements.txt

$ stt-model-manager
Traceback (most recent call last):
  File "/Users/andrew/.pyenv/versions/3.10.0/bin/stt-model-manager", line 5, in <module>
    from coqui_stt_model_manager.__main__ import main
  File "/Users/andrew/.pyenv/versions/3.10.0/lib/python3.10/site-packages/coqui_stt_model_manager/__main__.py", line 9, in <module>
    from .server import build_app, get_server_hostport, start_app
  File "/Users/andrew/.pyenv/versions/3.10.0/lib/python3.10/site-packages/coqui_stt_model_manager/server.py", line 19, in <module>
    from stt import Model
  File "/Users/andrew/.pyenv/versions/3.10.0/lib/python3.10/site-packages/stt/__init__.py", line 23, in <module>
    from stt.impl import Version as version
  File "/Users/andrew/.pyenv/versions/3.10.0/lib/python3.10/site-packages/stt/impl.py", line 13, in <module>
    from . import _impl
ImportError: dlopen(/Users/andrew/.pyenv/versions/3.10.0/lib/python3.10/site-packages/stt/_impl.cpython-310-darwin.so, 0x0002): tried: '/Users/andrew/.pyenv/versions/3.10.0/lib/python3.10/site-packages/stt/_impl.cpython-310-darwin.so' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64e'))
```

**Comment by wasertech** [comment]
This is an issue with STT on your platform, not with the model manager. If you can't install `stt` on your machine , then you can't use the manager.

If you are using Apple silicon, make sure you can install `stt` on your platform (python version + CPU arch. combo) first.

If you can install `stt` from the [pypi repo](https://pypi.org/project/stt/) using `pip install stt` then the model manger will be able to find the latest version of STT compatible with your platform by itself.

Otherwise, you can try to build and install `stt` yourself for your platform and then install the model manager.

I'll close this issue as there is nothing the manger can do. Checkout https://github.com/coqui-ai/STT/issues/2197 to see the status of this `ImportError` on Apple silicon macs.
